### ISSUE TITLE
Can you give more instructions please?

### ISSUE THREAD

**Issue by DanVettorazi** [ArmainAP/UnrealCam#2]
Hi! first of all, thanks for your contribution.
I installed the UnrealcamService and it seems that works (at least, now I have a webcam called UnrealCam)
But The example project doesn't open. It says that needs to be rebuild from the source and the plugin, if I place on my Plugins folder doesn't work too.
Can you explain how can I make this work? I'm using 4.25.3
Thanks so much!

**Comment by ArmainAP** [comment]
Hello!

That error means that Unreal build system did not build the source file automatically for an unknown reason, and you have to build them.

You have to right click on the .uproject file and then click 'Generate Visual Studio Files'.

The next step would be open the freshly created .sln file and hit build. 

If you still have any issue, please post it here and I will try to help you on it :)

**Comment by DanVettorazi** [comment]
It worked like a charm!
Thanks, man.
