### ISSUE TITLE
Cant get it working.

### ISSUE THREAD

**Issue by RonYanDaik** [ArmainAP/UnrealCam#3]
I get black screen. Testing it with Streamlabs.
Whats the order of things?
I need to run script inside Releasex64 and that's it?

**Comment by ArmainAP** [comment]
Yes, that is correct. I would also recommand a computer restart. 

It is supposed to work only with DirectShow compatible software.
DirectShow was already being deprecated by newer APIs when I created this repository. I do not know the current status of DirectShow compatible applications and if Streamlabs supported it...just as a note, I previously used to test this with OBS.

**Comment by RonYanDaik** [comment]
Thank you.
I had to restart computer, and now it works.

I have on more question:
Haw can you get transparent alpha with it? 
In the code i see it packs only 3 channels:
```
data[dataIndex + 2] = ColorBuffer[i].G;
data[dataIndex + 1] = ColorBuffer[i].R;
data[dataIndex] = ColorBuffer[i].B;
```
Also received image flipped and darker:
![image](https://user-images.githubusercontent.com/3350340/121318550-0415d280-c914-11eb-810d-f63a22589338.png)

**Comment by RonYanDaik** [comment]
Colors are inverted because UE4 engine has texture (that are not power of 4 dimension) in BGRA format.
